/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-03-26 10:49:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.Student;
import Dao.StudentDao;
import java.util.List;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("Dao.StudentDao");
    _jspx_imports_classes.add("Model.Student");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Provision Education</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"keywords\"\r\n");
      out.write("	content=\"Provision Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("	SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design\" />\r\n");
      out.write("<script>\r\n");
      out.write("	addEventListener(\"load\", function() {\r\n");
      out.write("		setTimeout(hideURLbar, 0);\r\n");
      out.write("	}, false);\r\n");
      out.write("\r\n");
      out.write("	function hideURLbar() {\r\n");
      out.write("		window.scrollTo(0, 1);\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/bootstrap.css\" type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("	media=\"all\">\r\n");
      out.write("<link href=\"css/style.css\" type=\"text/css\" rel=\"stylesheet\" media=\"all\">\r\n");
      out.write("<!-- font-awesome icons -->\r\n");
      out.write("<link href=\"css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- //Custom Theme files -->\r\n");
      out.write("<!-- online-fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- //online-fonts -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- main -->\r\n");
      out.write("	<div class=\"main-content\" id=\"home\">\r\n");
      out.write("		<!-- header -->\r\n");
      out.write("		<header>\r\n");
      out.write("			<div class=\"container-fluid\">\r\n");
      out.write("				<!-- nav -->\r\n");
      out.write("				<nav class=\"py-md-4 py-3 d-lg-flex nav_w3pvt\">\r\n");
      out.write("					<div id=\"logo\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							<a href=\"Index.jsp\">Provision</a>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("					<label for=\"drop\" class=\"toggle\"><span class=\"fa fa-bars\"></span></label>\r\n");
      out.write("					<input type=\"checkbox\" id=\"drop\" />\r\n");
      out.write("					<ul class=\"menu mt-lg-3 ml-auto\">\r\n");
      out.write("						<li class=\"active\"><a href=\"Index.jsp\">Home</a></li>\r\n");
      out.write("						<li><a href=\"about.html\">About Us</a></li>\r\n");
      out.write("						<li><a href=\"#exp\">Experience</a></li>\r\n");
      out.write("						<li><a href=\"course.html\" class=\"drop-text\">Courses</a></li>\r\n");
      out.write("						<!--  <li>\r\n");
      out.write("                            First Tier Drop Down\r\n");
      out.write("                            <label for=\"drop-2\" class=\"toggle\">Dropdown <span class=\"fa fa-angle-down\" aria-hidden=\"true\"></span>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <a href=\"#\">Dropdown <span class=\"fa fa-angle-down\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("                            <input type=\"checkbox\" id=\"drop-2\" />\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><a href=\"#team\" class=\"drop-text\">Professors</a></li>\r\n");
      out.write("                                <li><a href=\"#stats\" class=\"drop-text\">Statistics</a></li>\r\n");
      out.write("                                <li><a href=\"#test\" class=\"drop-text\">Reviews</a></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li> -->\r\n");
      out.write("						<li><a href=\"Student-Registration.jsp\">Register</a></li>\r\n");
      out.write("						<li><a href=\"Student-Login.jsp\">Login</a></li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<p class=\"w3pvt-phone\">\r\n");
      out.write("								<span class=\"fa fa-phone mr-2\"></span>+91 12345 67890\r\n");
      out.write("							</p>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</nav>\r\n");
      out.write("				<!-- //nav -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!-- //header -->\r\n");
      out.write("\r\n");
      out.write("		<!-- banner -->\r\n");
      out.write("		<div class=\"banner-content-w3pvt\">\r\n");
      out.write("			<div class=\"banner-w3layouts-info text-center\">\r\n");
      out.write("				<h3>Any successful career starts with a good Education</h3>\r\n");
      out.write("				<form class=\"banner-form\" method=\"post\" action=\"#\">\r\n");
      out.write("					<input type=\"email\" class=\"form-control\" id=\"Email\"\r\n");
      out.write("						placeholder=\"Enter your email...\" name=\"Email\" required=\"\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-default\">Get Started</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<!-- //banner -->\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //main -->\r\n");
      out.write("	<!-- /entry -->\r\n");
      out.write("	<div class=\"entry-w3pvt-main py-5\">\r\n");
      out.write("		<div class=\"container px-lg-5 py-md-3\">\r\n");
      out.write("			<div class=\"entry-w3layouts-info\">\r\n");
      out.write("				<h4>Best Online Learning Center</h4>\r\n");
      out.write("				<p>Maecenas quis neque libero. Class aptent taciti.Lorem ipsum\r\n");
      out.write("					dolor sit amet, consectetur adipiscing elit.Pellentesque convallis\r\n");
      out.write("					diam consequat magna vulputate malesuada. Cras a ornare elit. Nulla\r\n");
      out.write("					viverra pharetra sem, eget pulvinar neque pharetra ac.Pellentesque\r\n");
      out.write("					convallis diam consequat magna vulputate malesuada.</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- //entry -->\r\n");
      out.write("	<!-- banner-bottom -->\r\n");
      out.write("	<section class=\"banner-bottom py-5\" id=\"about\">\r\n");
      out.write("		<div class=\"container py-md-4\">\r\n");
      out.write("			<div class=\"row banner-grids\">\r\n");
      out.write("				<div class=\"col-lg-6 content-right-bottom text-left\">\r\n");
      out.write("					<img src=\"images/ab.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-lg-6 content-left-bottom entry-w3layouts-info text-left pl-lg-4\">\r\n");
      out.write("					<h5 class=\"mt-1\">Online Education Learn skills online.</h5>\r\n");
      out.write("					<h4>Limitless learning, more possibilities</h4>\r\n");
      out.write("					<p class=\"mt-2 text-left\">\r\n");
      out.write("						Integer pulvinar leo id viverra feugiat.<strong\r\n");
      out.write("							class=\"text-capitalize\"> Pellentesque libero justo,\r\n");
      out.write("							semper at tempus vel, ultrices in sed ligula. Nulla uter\r\n");
      out.write("							sollicitudin velit.</strong> Sed porttitor orci vel fermentum elit\r\n");
      out.write("						maximus. Curabitur ut turpis massa in condimentum libero.\r\n");
      out.write("						Pellentesque maximus Pellentesque libero justo Nulla uter\r\n");
      out.write("						sollicitudin velit. Sed porttitor orci vel ferm semper at vel,\r\n");
      out.write("						ultrices in ligula semper at vel.Curabitur ut turpis massa in\r\n");
      out.write("						condimentum libero.\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- //banner-bottom -->\r\n");
      out.write("	<!-- /team-content -->\r\n");
      out.write("	<section class=\"team-content py-5\" id=\"team\">\r\n");
      out.write("		<div class=\"container py-md-4 text-center\">\r\n");
      out.write("			<h3 class=\"tittle-w3layouts two\">Experienced Professors</h3>\r\n");
      out.write("			<div class=\"row team-grids text-center mt-md-5 mt-4\">\r\n");
      out.write("				<div class=\"col-lg-4 team-main\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"team-img\">\r\n");
      out.write("						<img src=\"images/t1.jpg\" alt=\"news image\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"team-info\">\r\n");
      out.write("\r\n");
      out.write("						<h4>Chester Roberson</h4>\r\n");
      out.write("						<small>Associate Professor</small>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing eiusmod\r\n");
      out.write("							tempor incididunt ut labore et dolore magna.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-4 team-main\">\r\n");
      out.write("					<div class=\"team-info\">\r\n");
      out.write("\r\n");
      out.write("						<h4>Maude Collier</h4>\r\n");
      out.write("						<small>Assistant Instructor</small>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing eiusmod\r\n");
      out.write("							tempor incididunt ut labore et dolore magna.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"team-img\">\r\n");
      out.write("						<img src=\"images/t2.jpg\" alt=\"news image\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-lg-4 team-main\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"team-img\">\r\n");
      out.write("						<img src=\"images/t3.jpg\" alt=\"news image\" class=\"img-fluid\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"team-info\">\r\n");
      out.write("\r\n");
      out.write("						<h4>Hunter Duncan</h4>\r\n");
      out.write("						<small>Assistant Instructor</small>\r\n");
      out.write("						<p>Lorem ipsum dolor sit amet, consectetur adipisicing eiusmod\r\n");
      out.write("							tempor incididunt ut labore et dolore magna.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- //team-content -->\r\n");
      out.write("	<!-- banner-bottom -->\r\n");
      out.write("	<section class=\"banner-bottom py-5\" id=\"exp\">\r\n");
      out.write("		<div class=\"container py-md-4\">\r\n");
      out.write("			<h3 class=\"tittle-w3layouts two text-center\">Live the experience</h3>\r\n");
      out.write("			<div class=\"row mid-grids mt-5\">\r\n");
      out.write("				<div class=\"col-md-5 content-w3pvt-img\">\r\n");
      out.write("					<img src=\"images/n1.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-md-7 content-left-bottom entry-w3layouts-info text-left mt-3\">\r\n");
      out.write("					<h5 class=\"mt-1\">You Can Learn Anything</h5>\r\n");
      out.write("					<h4>Learn at your own pace</h4>\r\n");
      out.write("					<p class=\"mt-2 text-left\">\r\n");
      out.write("						Integer pulvinar leo id viverra feugiat.<strong\r\n");
      out.write("							class=\"text-capitalize\"> Pellentesque libero justo,\r\n");
      out.write("							semper at tempus vel, ultrices in sed ligula. Nulla uter\r\n");
      out.write("							sollicitudin velit.</strong> Sed porttitor orci vel fermentum elit\r\n");
      out.write("						maximus. Curabitur ut turpis massa in condimentum libero.\r\n");
      out.write("						Pellentesque maximus Pellentesque libero justo Nulla uter\r\n");
      out.write("						sollicitudin velit. Sed porttitor orci vel ferm semper at vel,\r\n");
      out.write("						ultrices in ligula semper at vel.Curabitur ut turpis massa in\r\n");
      out.write("						condimentum libero.\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mid-grids my-lg-5 py-lg-5\">\r\n");
      out.write("\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-md-7 content-left-bottom entry-w3layouts-info text-left mt-3\">\r\n");
      out.write("					<h5 class=\"mt-1\">You Can Learn Anything</h5>\r\n");
      out.write("					<h4>Community of opportunities</h4>\r\n");
      out.write("					<p class=\"mt-2 text-left\">\r\n");
      out.write("						Integer pulvinar leo id viverra feugiat.<strong\r\n");
      out.write("							class=\"text-capitalize\"> Pellentesque libero justo,\r\n");
      out.write("							semper at tempus vel, ultrices in sed ligula. Nulla uter\r\n");
      out.write("							sollicitudin velit.</strong> Sed porttitor orci vel fermentum elit\r\n");
      out.write("						maximus. Curabitur ut turpis massa in condimentum libero.\r\n");
      out.write("						Pellentesque maximus Pellentesque libero justo Nulla uter\r\n");
      out.write("						sollicitudin velit. Sed porttitor orci vel ferm semper at vel,\r\n");
      out.write("						ultrices in ligula semper at vel.Curabitur ut turpis massa in\r\n");
      out.write("						condimentum libero.\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-5 content-w3pvt-img\">\r\n");
      out.write("					<img src=\"images/n2.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row mid-grids\">\r\n");
      out.write("				<div class=\"col-md-5 content-w3pvt-img\">\r\n");
      out.write("					<img src=\"images/n3.jpg\" alt=\"\" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"col-md-7 content-left-bottom entry-w3layouts-info text-left mt-3\">\r\n");
      out.write("					<h5 class=\"mt-1\">You Can Learn Anything</h5>\r\n");
      out.write("					<h4>Official certificate</h4>\r\n");
      out.write("					<p class=\"mt-2 text-left\">\r\n");
      out.write("						Integer pulvinar leo id viverra feugiat.<strong\r\n");
      out.write("							class=\"text-capitalize\"> Pellentesque libero justo,\r\n");
      out.write("							semper at tempus vel, ultrices in sed ligula. Nulla uter\r\n");
      out.write("							sollicitudin velit.</strong> Sed porttitor orci vel fermentum elit\r\n");
      out.write("						maximus. Curabitur ut turpis massa in condimentum libero.\r\n");
      out.write("						Pellentesque maximus Pellentesque libero justo Nulla uter\r\n");
      out.write("						sollicitudin velit. Sed porttitor orci vel ferm semper at vel,\r\n");
      out.write("						ultrices in ligula semper at vel.Curabitur ut turpis massa in\r\n");
      out.write("						condimentum libero.\r\n");
      out.write("					</p>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- //banner-bottom -->\r\n");
      out.write("	<!--/last-content-->\r\n");
      out.write("	<section class=\"last-content text py-5\">\r\n");
      out.write("		<div class=\"container py-md-3 text-center\">\r\n");
      out.write("			<div class=\"last-w3pvt-inner-content px-lg-5\">\r\n");
      out.write("				<h3 class=\"mb-4 tittle-w3layouts\">\r\n");
      out.write("					Get started with <span>Online </span> Education !\r\n");
      out.write("				</h3>\r\n");
      out.write("				<p class=\"px-lg-5\">Sed ut perspiciatis unde omnis natus error\r\n");
      out.write("					dolor volup tatem ed accus antium dolor emque laudantium, totam rem\r\n");
      out.write("					aperiam, eaqu ipsa quae ab illo quasi architi ecto beatae vitae\r\n");
      out.write("					dicta sunt dolor ipsum.</p>\r\n");
      out.write("				<div class=\"buttons mt-md-4 mt-3\">\r\n");
      out.write("					<a href=\"apply.html\" class=\"btn btn-default\">Get Started</a> <a\r\n");
      out.write("						href=\"apply.html\" class=\"btn btn1\"> Join Event </a>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--//last-content-->\r\n");
      out.write("	<section class=\"ab-info-main py-5\">\r\n");
      out.write("		<div class=\"container py-md-4\">\r\n");
      out.write("			<h3 class=\"tittle-w3layouts two text-center\">Available Courses</h3>\r\n");
      out.write("			<div id=\"products\" class=\"row view-group my-lg-5 my-4\">\r\n");
      out.write("				<div class=\"item col-lg-4 mt-3\">\r\n");
      out.write("					<div class=\"thumbnail card\">\r\n");
      out.write("						<div class=\"img-event\">\r\n");
      out.write("							<img class=\"group list-group-image img-fluid\" src=\"images/g1.jpg\"\r\n");
      out.write("								alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"caption card-body\">\r\n");
      out.write("							<h4 class=\"group card-title inner list-group-item-heading\">\r\n");
      out.write("								Programming</h4>\r\n");
      out.write("							<p class=\"group inner list-group-item-text\">Lorem ipsum dolor\r\n");
      out.write("								sit amet consectetuer, consectetuer adipiscing elit sit</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item col-lg-4 mt-3\">\r\n");
      out.write("					<div class=\"thumbnail card\">\r\n");
      out.write("						<div class=\"img-event\">\r\n");
      out.write("							<img class=\"group list-group-image img-fluid\" src=\"images/g2.jpg\"\r\n");
      out.write("								alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"caption card-body\">\r\n");
      out.write("							<h4 class=\"group card-title inner list-group-item-heading\">\r\n");
      out.write("								Art &amp; Design</h4>\r\n");
      out.write("							<p class=\"group inner list-group-item-text\">Lorem ipsum dolor\r\n");
      out.write("								sit amet consectetuer, consectetuer adipiscing elit sit</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"item col-lg-4 mt-3\">\r\n");
      out.write("					<div class=\"thumbnail card\">\r\n");
      out.write("						<div class=\"img-event\">\r\n");
      out.write("							<img class=\"group list-group-image img-fluid\" src=\"images/g3.jpg\"\r\n");
      out.write("								alt=\"\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"caption card-body\">\r\n");
      out.write("							<h4 class=\"group card-title inner list-group-item-heading\">\r\n");
      out.write("								Languages</h4>\r\n");
      out.write("							<p class=\"group inner list-group-item-text\">Lorem ipsum dolor\r\n");
      out.write("								sit amet consectetuer, consectetuer adipiscing elit sit</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row text-center mt-lg-5 mt-4 pt-5\" id=\"stats\">\r\n");
      out.write("				<div class=\"col-sm-4\">\r\n");
      out.write("					<div class=\"counter\">\r\n");
      out.write("						<h3 class=\"count-title\">1500</h3>\r\n");
      out.write("						<p class=\"count-text \">Support</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-4\">\r\n");
      out.write("					<div class=\"counter two\">\r\n");
      out.write("						<h3 class=\"count-title\">1700</h3>\r\n");
      out.write("						<p class=\"count-text \">Happy Hours</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-4\">\r\n");
      out.write("					<div class=\"counter\">\r\n");
      out.write("						<h3 class=\"count-title\">11900</h3>\r\n");
      out.write("						<p class=\"count-text \">Project Complete</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--//-->\r\n");
      out.write("	<!--/testimonials-->\r\n");
      out.write("	<section class=\"testimonials py-5\" id=\"test\">\r\n");
      out.write("		<div class=\"container py-3\">\r\n");
      out.write("			<h3 class=\"tittle-w3layouts text-center mt-3\">See what people\r\n");
      out.write("				are saying</h3>\r\n");
      out.write("			<div class=\"testimonials_grid mx-auto text-center row px-lg-5 mt-5\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-md-3 testi_grid text-md-center\">\r\n");
      out.write("					<img src=\"images/test.jpg\" alt=\" \" class=\"img-fluid\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-md-9 testi_grid text-left\">\r\n");
      out.write("					<span class=\"fa fa-quote-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("					<p class=\"sub-test pr-lg-5\">Integer sit amet mattis quam, sit\r\n");
      out.write("						amet ultricies velit. Nam libero tempore, cum soluta nobis est\r\n");
      out.write("						eligendi optio cumque nihil impedit quo minus id quod possimus,\r\n");
      out.write("						omnis voluptas.\r\n");
      out.write("					<h5>Thomas Carl</h5>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!--//testimonials-->\r\n");
      out.write("	<!-- footer -->\r\n");
      out.write("	<footer class=\"footer-content text-center py-5\">\r\n");
      out.write("		<div class=\"container py-md-3\">\r\n");
      out.write("			<!-- logo -->\r\n");
      out.write("			<h2 class=\"logo2 text-center\">\r\n");
      out.write("				<a href=\"index.html\"> Provision </a>\r\n");
      out.write("			</h2>\r\n");
      out.write("			<!-- //logo -->\r\n");
      out.write("			<!-- address -->\r\n");
      out.write("			<div class=\"contact-left-footer mt-md-4\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<p>\r\n");
      out.write("							<span class=\"fa fa-map-marker mr-2\"></span>Somewhere on Earth\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"mx-4\">\r\n");
      out.write("						<p>\r\n");
      out.write("							<span class=\"fa fa-phone mr-2\"></span>+91 12345 67890\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<p class=\"text-wh\">\r\n");
      out.write("							<span class=\"fa fa-envelope-open mr-2\"></span> <a\r\n");
      out.write("								href=\"mailto:dkwebdeveloper9@gmail.com\">dkwebdeveloper9@gmail.com</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //address -->\r\n");
      out.write("			<!-- social icons -->\r\n");
      out.write("			<div class=\"footer-w3pvt-copy-social my-4\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"#\"> <span class=\"fa fa-facebook-square\"></span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"mx-2\"><a href=\"#\"> <span\r\n");
      out.write("							class=\"fa fa-twitter-square\"></span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"\"><a href=\"#\"> <span\r\n");
      out.write("							class=\"fa fa-google-plus-square\"></span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"mx-2\"><a href=\"#\"> <span\r\n");
      out.write("							class=\"fa fa-linkedin-square\"></span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li><a href=\"#\"> <span class=\"fa fa-rss-square\"></span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("					<li class=\"ml-2\"><a href=\"#\"> <span\r\n");
      out.write("							class=\"fa fa-pinterest-square\"></span>\r\n");
      out.write("					</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //social icons -->\r\n");
      out.write("			<!-- copyright -->\r\n");
      out.write("			<div class=\"w3layouts-copy text-center\">\r\n");
      out.write("				<p class=\"text-da\">© 2023 Provision. All rights reserved |\r\n");
      out.write("					Design by DK</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //copyright -->\r\n");
      out.write("			<!-- move top icon -->\r\n");
      out.write("			<div class=\"move-top text-center mt-3\">\r\n");
      out.write("				<a href=\"#home\" class=\"move-top\"><span\r\n");
      out.write("					class=\"fa fa-angle-double-up\" aria-hidden=\"true\"></span></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- //move top icon -->\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<!-- //footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
